const estadosBrasileiros = [
  {
    id: 1,
    nome: "Acre",
    sigla: "AC",
    capital: "Rio Branco",
    habitantes: 869265,
  },
  {
    id: 2,
    nome: "Alagoas",
    sigla: "AL",
    capital: "Maceió",
    habitantes: 3322820,
  },
  { id: 3, nome: "Amapa", sigla: "AP", capital: "Macapa", habitantes: 861773 },
  {
    id: 4,
    nome: "Amazonas",
    sigla: "AM",
    capital: "Manaus",
    habitantes: 4207714,
  },
  {
    id: 5,
    nome: "Bahia",
    sigla: "BA",
    capital: "Salvador",
    habitantes: 14873064,
  },
  {
    id: 6,
    nome: "Ceara",
    sigla: "CE",
    capital: "Fortaleza",
    habitantes: 9132078,
  },
  {
    id: 7,
    nome: "Distrito Federal",
    sigla: "DF",
    capital: "Brasília",
    habitantes: 3055149,
  },
  {
    id: 8,
    nome: "Espírito Santo",
    sigla: "ES",
    capital: "Vitória",
    habitantes: 4018650,
  },
  {
    id: 9,
    nome: "Goias",
    sigla: "GO",
    capital: "Goiânia",
    habitantes: 7113540,
  },
  {
    id: 10,
    nome: "Maranhão",
    sigla: "MA",
    capital: "São Luís",
    habitantes: 7114598,
  },
  {
    id: 11,
    nome: "Mato Grosso",
    sigla: "MT",
    capital: "Cuiaba",
    habitantes: 3526220,
  },
  {
    id: 12,
    nome: "Mato Grosso do Sul",
    sigla: "MS",
    capital: "Campo Grande",
    habitantes: 2809394,
  },
  {
    id: 13,
    nome: "Minas Gerais",
    sigla: "MG",
    capital: "Belo Horizonte",
    habitantes: 21292666,
  },
  { id: 14, nome: "Para", sigla: "PA", capital: "Belém", habitantes: 8690745 },
  {
    id: 15,
    nome: "Paraíba",
    sigla: "PB",
    capital: "João Pessoa",
    habitantes: 4039277,
  },
  {
    id: 16,
    nome: "Parana",
    sigla: "PR",
    capital: "Curitiba",
    habitantes: 11516840,
  },
  {
    id: 17,
    nome: "Pernambuco",
    sigla: "PE",
    capital: "Recife",
    habitantes: 9616621,
  },
  {
    id: 18,
    nome: "Piauí",
    sigla: "PI",
    capital: "Teresina",
    habitantes: 3273227,
  },
  {
    id: 19,
    nome: "Rio de Janeiro",
    sigla: "RJ",
    capital: "Rio de Janeiro",
    habitantes: 17366189,
  },
  {
    id: 20,
    nome: "Rio Grande do Norte",
    sigla: "RN",
    capital: "Natal",
    habitantes: 3534165,
  },
  {
    id: 21,
    nome: "Rio Grande do Sul",
    sigla: "RS",
    capital: "Porto Alegre",
    habitantes: 11422973,
  },
  {
    id: 22,
    nome: "Rondônia",
    sigla: "RO",
    capital: "Porto Velho",
    habitantes: 1796460,
  },
  {
    id: 23,
    nome: "Roraima",
    sigla: "RR",
    capital: "Boa Vista",
    habitantes: 652713,
  },
  {
    id: 24,
    nome: "Santa Catarina",
    sigla: "SC",
    capital: "Florianópolis",
    habitantes: 7252502,
  },
  {
    id: 25,
    nome: "São Paulo",
    sigla: "SP",
    capital: "São Paulo",
    habitantes: 46289333,
  },
  {
    id: 26,
    nome: "Sergipe",
    sigla: "SE",
    capital: "Aracaju",
    habitantes: 2318822,
  },
  {
    id: 27,
    nome: "Tocantins",
    sigla: "TO",
    capital: "Palmas",
    habitantes: 1590248,
  },
];

const continentes = [
  {
    nome: "Africa",
    paises: [
      {
        id: 1,
        nome: "Africa do Sul",
        presidente: "Cyril Ramaphosa",
        habitantes: 60041956,
        territorio: "1,221,037 km²",
      },
      {
        id: 2,
        nome: "Argelia",
        presidente: "Abdelmadjid Tebboune",
        habitantes: 43851044,
        territorio: "2,381,741 km²",
      },
      {
        id: 3,
        nome: "Angola",
        presidente: "Joao Lourenco",
        habitantes: 32866272,
        territorio: "1,246,700 km²",
      },
      {
        id: 4,
        nome: "Benin",
        presidente: "Patrice Talon",
        habitantes: 12123200,
        territorio: "114,763 km²",
      },
      {
        id: 5,
        nome: "Botsuana",
        presidente: "Mokgweetsi Masisi",
        habitantes: 2351627,
        territorio: "581,730 km²",
      },
      {
        id: 6,
        nome: "Burquina Faso",
        presidente: "Roch Marc Christian Kabore",
        habitantes: 20244080,
        territorio: "272,967 km²",
      },
      {
        id: 7,
        nome: "Burundi",
        presidente: "Evariste Ndayishimiye",
        habitantes: 11890784,
        territorio: "27,834 km²",
      },
      {
        id: 8,
        nome: "Cabo Verde",
        presidente: "Jose Maria Neves",
        habitantes: 555987,
        territorio: "4,033 km²",
      },
      {
        id: 9,
        nome: "Camaroes",
        presidente: "Paul Biya",
        habitantes: 26545863,
        territorio: "475,442 km²",
      },
      {
        id: 10,
        nome: "Chade",
        presidente: "Mahamat Deby",
        habitantes: 16877000,
        territorio: "1,284,000 km²",
      },
      {
        id: 11,
        nome: "Comores",
        presidente: "Azali Assoumani",
        habitantes: 873724,
        territorio: "1,862 km²",
      },
      {
        id: 12,
        nome: "Republica Democratica do Congo",
        presidente: "Felix Tshisekedi",
        habitantes: 101780263,
        territorio: "2,344,858 km²",
      },
      {
        id: 13,
        nome: "Djibuti",
        presidente: "Ismaïl Omar Guelleh",
        habitantes: 1078373,
        territorio: "23,200 km²",
      },
      {
        id: 14,
        nome: "Egito",
        presidente: "Abdel Fattah el-Sisi",
        habitantes: 100075480,
        territorio: "1,001,450 km²",
      },
      {
        id: 15,
        nome: "Guine Equatorial",
        presidente: "Teodoro Obiang Nguema Mbasogo",
        habitantes: 1454789,
        territorio: "28,051 km²",
      },
      {
        id: 16,
        nome: "Eritreia",
        presidente: "Isaias Afwerki",
        habitantes: 3546421,
        territorio: "117,600 km²",
      },
      {
        id: 17,
        nome: "Eswatini",
        presidente: "Mswati III",
        habitantes: 1160164,
        territorio: "17,364 km²",
      },
      {
        id: 18,
        nome: "Etiopia",
        presidente: "Sahle-Work Zewde",
        habitantes: 114963588,
        territorio: "1,104,300 km²",
      },
      {
        id: 19,
        nome: "Gabao",
        presidente: "Ali Bongo Ondimba",
        habitantes: 2225734,
        territorio: "267,668 km²",
      },
      {
        id: 20,
        nome: "Gambia",
        presidente: "Adama Barrow",
        habitantes: 2347706,
        territorio: "11,295 km²",
      },
      {
        id: 21,
        nome: "Gana",
        presidente: "Nana Akufo-Addo",
        habitantes: 31072940,
        territorio: "238,533 km²",
      },
      {
        id: 22,
        nome: "Guine",
        presidente: "Alpha Conde",
        habitantes: 13132795,
        territorio: "245,857 km²",
      },
      {
        id: 23,
        nome: "Guine-Bissau",
        presidente: "Umaro Sissoco Embalo",
        habitantes: 1968001,
        territorio: "36,125 km²",
      },
      {
        id: 24,
        nome: "Costa do Marfim",
        presidente: "Alassane Ouattara",
        habitantes: 25823071,
        territorio: "322,463 km²",
      },
      {
        id: 25,
        nome: "Quenia",
        presidente: "William Ruto",
        habitantes: 47615739,
        territorio: "580,367 km²",
      },
      {
        id: 26,
        nome: "Lesoto",
        presidente: "Mothetjoa Metsing",
        habitantes: 2142249,
        territorio: "30,355 km²",
      },
      {
        id: 27,
        nome: "Liberia",
        presidente: "George Weah",
        habitantes: 5057681,
        territorio: "111,369 km²",
      },
      {
        id: 28,
        nome: "Libia",
        presidente: "Abdul Hamid Dbeibeh",
        habitantes: 6871292,
        territorio: "1,759,541 km²",
      },
      {
        id: 29,
        nome: "Madagascar",
        presidente: "Andry Rajoelina",
        habitantes: 27691018,
        territorio: "587,041 km²",
      },
      {
        id: 30,
        nome: "Malaui",
        presidente: "Lazarus Chakwera",
        habitantes: 19129952,
        territorio: "118,484 km²",
      },
      {
        id: 31,
        nome: "Mali",
        presidente: "Assimi Goita",
        habitantes: 20250833,
        territorio: "1,240,192 km²",
      },
      {
        id: 32,
        nome: "Mauritania",
        presidente: "Mohamed Ould Ghazouani",
        habitantes: 4649658,
        territorio: "1,030,700 km²",
      },
      {
        id: 33,
        nome: "Mauricio",
        presidente: "Prithvirajsing Roopun",
        habitantes: 1265985,
        territorio: "2,040 km²",
      },
      {
        id: 34,
        nome: "Marrocos",
        presidente: "Aziz Akhannouch",
        habitantes: 36886000,
        territorio: "446,550 km²",
      },
      {
        id: 35,
        nome: "Mocambique",
        presidente: "Filipe Nyusi",
        habitantes: 33627682,
        territorio: "801,590 km²",
      },
      {
        id: 36,
        nome: "Namibia",
        presidente: "Hage Geingob",
        habitantes: 2587801,
        territorio: "825,615 km²",
      },
      {
        id: 37,
        nome: "Niger",
        presidente: "Mohamed Bazoum",
        habitantes: 24420000,
        territorio: "1,267,000 km²",
      },
      {
        id: 38,
        nome: "Nigeria",
        presidente: "Muhammadu Buhari",
        habitantes: 211400708,
        territorio: "923,768 km²",
      },
      {
        id: 39,
        nome: "Ruanda",
        presidente: "Paul Kagame",
        habitantes: 13228282,
        territorio: "26,338 km²",
      },
      {
        id: 40,
        nome: "Santa Helena, Ascensao e Tristao da Cunha",
        presidente: "Philip Rushbrook",
        habitantes: 5633,
        territorio: "420 km²",
      },
      {
        id: 41,
        nome: "Saara Ocidental",
        presidente: "Brahim Ghali",
        habitantes: 567402,
        territorio: "266,000 km²",
      },
      {
        id: 42,
        nome: "Sao Tome e Principe",
        presidente: "Carlos Vila Nova",
        habitantes: 219159,
        territorio: "964 km²",
      },
      {
        id: 43,
        nome: "Senegal",
        presidente: "Macky Sall",
        habitantes: 16743927,
        territorio: "196,722 km²",
      },
      {
        id: 44,
        nome: "Seychelles",
        presidente: "Wavel Ramkalawan",
        habitantes: 98347,
        territorio: "459 km²",
      },
      {
        id: 45,
        nome: "Serra Leoa",
        presidente: "Julius Maada Bio",
        habitantes: 7976983,
        territorio: "71,740 km²",
      },
      {
        id: 46,
        nome: "Somalia",
        presidente: "Hassan Sheikh Mohamud",
        habitantes: 12001000,
        territorio: "637,657 km²",
      },
      {
        id: 47,
        nome: "Sudao do Sul",
        presidente: "Salva Kiir Mayardit",
        habitantes: 11193725,
        territorio: "619,745 km²",
      },
      {
        id: 48,
        nome: "Sudao",
        presidente: "Abdalla Hamdok",
        habitantes: 44909353,
        territorio: "1,861,484 km²",
      },
      {
        id: 49,
        nome: "Tanzania",
        presidente: "Samia Suluhu",
        habitantes: 59734218,
        territorio: "945,087 km²",
      },
      {
        id: 50,
        nome: "Togo",
        presidente: "Faure Gnassingbe",
        habitantes: 8278724,
        territorio: "56,785 km²",
      },
      {
        id: 51,
        nome: "Tunisia",
        presidente: "Kais Saied",
        habitantes: 11818619,
        territorio: "163,610 km²",
      },
      {
        id: 52,
        nome: "Uganda",
        presidente: "Yoweri Museveni",
        habitantes: 47253000,
        territorio: "241,550 km²",
      },
      {
        id: 53,
        nome: "Zambia",
        presidente: "Hakainde Hichilema",
        habitantes: 18383955,
        territorio: "752,612 km²",
      },
      {
        id: 54,
        nome: "Zimbabue",
        presidente: "Emmerson Mnangagwa",
        habitantes: 15092171,
        territorio: "390,757 km²",
      },
    ],
  },
  {
    nome: "America do Norte",
    paises: [
      {
        id: 1,
        nome: "Antigua e Barbuda",
        presidente: "Gaston Browne",
        habitantes: 97929,
        territorio: "442 km²",
      },
      {
        id: 2,
        nome: "Bahamas",
        presidente: "Philip Davis",
        habitantes: 393244,
        territorio: "13,878 km²",
      },
      {
        id: 3,
        nome: "Barbados",
        presidente: "Sandra Mason",
        habitantes: 287375,
        territorio: "430 km²",
      },
      {
        id: 4,
        nome: "Belize",
        presidente: "Johnny Briceño",
        habitantes: 419199,
        territorio: "22,966 km²",
      },
      {
        id: 5,
        nome: "Canada",
        presidente: "Justin Trudeau",
        habitantes: 37742154,
        territorio: "9,984,670 km²",
      },
      {
        id: 6,
        nome: "Costa Rica",
        presidente: "Rodrigo Chaves Robles",
        habitantes: 5143459,
        territorio: "51,100 km²",
      },
      {
        id: 7,
        nome: "Cuba",
        presidente: "Miguel Díaz-Canel",
        habitantes: 11326616,
        territorio: "109,884 km²",
      },
      {
        id: 8,
        nome: "Dominica",
        presidente: "Roosevelt Skerrit",
        habitantes: 71986,
        territorio: "751 km²",
      },
      {
        id: 9,
        nome: "El Salvador",
        presidente: "Nayib Bukele",
        habitantes: 6486201,
        territorio: "21,041 km²",
      },
      {
        id: 10,
        nome: "Granada",
        presidente: "Charles Peter David",
        habitantes: 112003,
        territorio: "344 km²",
      },
      {
        id: 11,
        nome: "Guatemala",
        presidente: "Alejandro Giammattei",
        habitantes: 17915568,
        territorio: "108,889 km²",
      },
      {
        id: 12,
        nome: "Haiti",
        presidente: "Ariel Henry",
        habitantes: 11402533,
        territorio: "27,750 km²",
      },
      {
        id: 13,
        nome: "Honduras",
        presidente: "Xiomara Castro",
        habitantes: 10056592,
        territorio: "112,492 km²",
      },
      {
        id: 14,
        nome: "Jamaica",
        presidente: "Andrew Holness",
        habitantes: 2961161,
        territorio: "10,991 km²",
      },
      {
        id: 15,
        nome: "Mexico",
        presidente: "Andrés Manuel López Obrador",
        habitantes: 126190788,
        territorio: "1,964,375 km²",
      },
      {
        id: 16,
        nome: "Nicaragua",
        presidente: "Daniel Ortega",
        habitantes: 6624554,
        territorio: "130,373 km²",
      },
      {
        id: 17,
        nome: "Panama",
        presidente: "Laurentino Cortizo",
        habitantes: 4314767,
        territorio: "75,420 km²",
      },
      {
        id: 18,
        nome: "São Cristóvão e Névis",
        presidente: "Terrance Drew",
        habitantes: 53199,
        territorio: "261 km²",
      },
      {
        id: 19,
        nome: "Santa Lúcia",
        presidente: "Philip J. Pierre",
        habitantes: 184999,
        territorio: "617 km²",
      },
      {
        id: 20,
        nome: "São Vicente e Granadinas",
        presidente: "Carlos James",
        habitantes: 110608,
        territorio: "389 km²",
      },
      {
        id: 21,
        nome: "Trinidad e Tobago",
        presidente: "Paula-Mae Weekes",
        habitantes: 1409000,
        territorio: "5,130 km²",
      },
      {
        id: 22,
        nome: "Estados Unidos",
        presidente: "Joe Biden",
        habitantes: 331449281,
        territorio: "9,629,091 km²",
      },
    ],
  },
  {
    nome: "America do Sul",
    paises: [
      {
        id: 1,
        nome: "Argentina",
        presidente: "Alberto Fernandez",
        habitantes: 45195777,
        territorio: "2,780,400 km²",
      },
      {
        id: 2,
        nome: "Bolivia",
        presidente: "Luis Arce",
        habitantes: 11633371,
        territorio: "1,098,581 km²",
      },
      {
        id: 3,
        nome: "Brasil",
        presidente: "Jair Bolsonaro",
        habitantes: 213993437,
        territorio: "8,515,767 km²",
      },
      {
        id: 4,
        nome: "Chile",
        presidente: "Gabriel Boric",
        habitantes: 19116201,
        territorio: "756,096 km²",
      },
      {
        id: 5,
        nome: "Colombia",
        presidente: "Gustavo Petro",
        habitantes: 50339443,
        territorio: "1,141,748 km²",
      },
      {
        id: 6,
        nome: "Equador",
        presidente: "Guillermo Lasso",
        habitantes: 17688599,
        territorio: "283,561 km²",
      },
      {
        id: 7,
        nome: "Guiana",
        presidente: "Mohamed Irfaan Ali",
        habitantes: 786508,
        territorio: "214,969 km²",
      },
      {
        id: 8,
        nome: "Paraguai",
        presidente: "Mario Abdo Benitez",
        habitantes: 7132530,
        territorio: "406,752 km²",
      },
      {
        id: 9,
        nome: "Peru",
        presidente: "Dina Boluarte",
        habitantes: 33543549,
        territorio: "1,285,216 km²",
      },
      {
        id: 10,
        nome: "Suriname",
        presidente: "Chandrikapersad Santokhi",
        habitantes: 586632,
        territorio: "163,820 km²",
      },
      {
        id: 11,
        nome: "Uruguai",
        presidente: "Luis Lacalle Pou",
        habitantes: 3473727,
        territorio: "176,215 km²",
      },
      {
        id: 12,
        nome: "Venezuela",
        presidente: "Nicolas Maduro",
        habitantes: 28435940,
        territorio: "916,445 km²",
      },
    ],
  },
  {
    nome: "Asia",
    paises: [
      {
        id: 1,
        nome: "Afeganistao",
        presidente: "Ashraf Ghani",
        habitantes: 37171921,
        territorio: "652,230 km²",
      },
      {
        id: 2,
        nome: "Arabia Saudita",
        presidente: "Salman bin Abdulaziz Al Saud",
        habitantes: 34813871,
        territorio: "2,149,690 km²",
      },
      {
        id: 3,
        nome: "Armenia",
        presidente: "Armen Sargsyan",
        habitantes: 2963243,
        territorio: "29,743 km²",
      },
      {
        id: 4,
        nome: "Azerbaijao",
        presidente: "Ilham Aliyev",
        habitantes: 10139177,
        territorio: "86,600 km²",
      },
      {
        id: 5,
        nome: "Bahrein",
        presidente: "Hamad bin Isa Al Khalifa",
        habitantes: 1543300,
        territorio: "760 km²",
      },
      {
        id: 6,
        nome: "Bangladesh",
        presidente: "Abdul Hamid",
        habitantes: 166303498,
        territorio: "147,570 km²",
      },
      {
        id: 7,
        nome: "Bhutao",
        presidente: "Lotay Tshering",
        habitantes: 763092,
        territorio: "38,394 km²",
      },
      {
        id: 8,
        nome: "Birmania",
        presidente: "Win Myint",
        habitantes: 54045420,
        territorio: "676,578 km²",
      },
      {
        id: 9,
        nome: "Brunei",
        presidente: "Hassanal Bolkiah",
        habitantes: 434076,
        territorio: "5,765 km²",
      },
      {
        id: 10,
        nome: "Butao",
        presidente: "Lotay Tshering",
        habitantes: 763092,
        territorio: "38,394 km²",
      },
      {
        id: 11,
        nome: "Camboja",
        presidente: "Hun Sen",
        habitantes: 16718965,
        territorio: "181,035 km²",
      },
      {
        id: 12,
        nome: "Cazaquistao",
        presidente: "Kassym-Jomart Tokayev",
        habitantes: 18916438,
        territorio: "2,724,900 km²",
      },
      {
        id: 13,
        nome: "China",
        presidente: "Xi Jinping",
        habitantes: 1439323776,
        territorio: "9,596,961 km²",
      },
      {
        id: 14,
        nome: "Chipre",
        presidente: "Nicos Anastasiades",
        habitantes: 1207359,
        territorio: "9,251 km²",
      },
      {
        id: 15,
        nome: "Coreia do Norte",
        presidente: "Kim Jong-un",
        habitantes: 25778816,
        territorio: "120,538 km²",
      },
      {
        id: 16,
        nome: "Coreia do Sul",
        presidente: "Moon Jae-in",
        habitantes: 51780579,
        territorio: "100,210 km²",
      },
      {
        id: 17,
        nome: "Emirados Arabes Unidos",
        presidente: "Khalifa bin Zayed Al Nahyan",
        habitantes: 9890402,
        territorio: "83,600 km²",
      },
      {
        id: 18,
        nome: "Georgia",
        presidente: "Salome Zurabishvili",
        habitantes: 3989167,
        territorio: "69,700 km²",
      },
      {
        id: 19,
        nome: "India",
        presidente: "Ram Nath Kovind",
        habitantes: 1393409038,
        territorio: "3,287,263 km²",
      },
      {
        id: 20,
        nome: "Indonesia",
        presidente: "Joko Widodo",
        habitantes: 276361783,
        territorio: "1,904,569 km²",
      },
      {
        id: 21,
        nome: "Ira",
        presidente: "Ebrahim Raisi",
        habitantes: 85193794,
        territorio: "1,648,195 km²",
      },
      {
        id: 22,
        nome: "Iraque",
        presidente: "Barham Salih",
        habitantes: 41272625,
        territorio: "438,317 km²",
      },
      {
        id: 23,
        nome: "Israel",
        presidente: "Isaac Herzog",
        habitantes: 9242074,
        territorio: "22,072 km²",
      },
      {
        id: 24,
        nome: "Japao",
        presidente: "Fumio Kishida",
        habitantes: 125584838,
        territorio: "377,975 km²",
      },
      {
        id: 25,
        nome: "Jordania",
        presidente: "Abdullah II",
        habitantes: 10203134,
        territorio: "89,342 km²",
      },
      {
        id: 26,
        nome: "Quirguistao",
        presidente: "Sadyr Japarov",
        habitantes: 6628550,
        territorio: "199,951 km²",
      },
      {
        id: 27,
        nome: "Laos",
        presidente: "Thongloun Sisoulith",
        habitantes: 7368295,
        territorio: "236,800 km²",
      },
      {
        id: 28,
        nome: "Libano",
        presidente: "Michel Aoun",
        habitantes: 6825442,
        territorio: "10,452 km²",
      },
      {
        id: 29,
        nome: "Maldivas",
        presidente: "Ibrahim Mohamed Solih",
        habitantes: 540542,
        territorio: "298 km²",
      },
      {
        id: 30,
        nome: "Malasia",
        presidente: "Anwar Ibrahim",
        habitantes: 32365999,
        territorio: "330,803 km²",
      },
      {
        id: 31,
        nome: "Mongolia",
        presidente: "Khurelsukh Ukhnaa",
        habitantes: 3278290,
        territorio: "1,564,116 km²",
      },
      {
        id: 32,
        nome: "Nepal",
        presidente: "Bidhya Devi Bhandari",
        habitantes: 29609504,
        territorio: "147,516 km²",
      },
      {
        id: 33,
        nome: "Oma",
        presidente: "Haitham bin Tariq",
        habitantes: 5106626,
        territorio: "309,500 km²",
      },
      {
        id: 34,
        nome: "Paquistao",
        presidente: "Arif Alvi",
        habitantes: 225199937,
        territorio: "881,913 km²",
      },
      {
        id: 35,
        nome: "Filipinas",
        presidente: "Rodrigo Duterte",
        habitantes: 111046913,
        territorio: "300,000 km²",
      },
      {
        id: 36,
        nome: "Catar",
        presidente: "Tamim bin Hamad Al Thani",
        habitantes: 2832071,
        territorio: "11,586 km²",
      },
      {
        id: 37,
        nome: "Russia",
        presidente: "Vladimir Putin",
        habitantes: 145912025,
        territorio: "17,098,242 km²",
      },
      {
        id: 38,
        nome: "Arabia Saudita",
        presidente: "Salman bin Abdulaziz Al Saud",
        habitantes: 34813871,
        territorio: "2,149,690 km²",
      },
      {
        id: 39,
        nome: "Singapura",
        presidente: "Halimah Yacob",
        habitantes: 5850342,
        territorio: "728 km²",
      },
      {
        id: 40,
        nome: "Sri Lanka",
        presidente: "Gotabaya Rajapaksa",
        habitantes: 21413249,
        territorio: "65,610 km²",
      },
      {
        id: 41,
        nome: "Siria",
        presidente: "Bashar al-Assad",
        habitantes: 17500658,
        territorio: "185,180 km²",
      },
      {
        id: 42,
        nome: "Tajiquistao",
        presidente: "Emomali Rahmon",
        habitantes: 9749000,
        territorio: "143,100 km²",
      },
      {
        id: 43,
        nome: "Tailandia",
        presidente: "Prayut Chan-o-cha",
        habitantes: 69799978,
        territorio: "513,120 km²",
      },
      {
        id: 44,
        nome: "Turquia",
        presidente: "Recep Tayyip Erdogan",
        habitantes: 84937885,
        territorio: "783,356 km²",
      },
      {
        id: 45,
        nome: "Turcomenistao",
        presidente: "Gurbanguly Berdimuhamedow",
        habitantes: 6031200,
        territorio: "491,210 km²",
      },
      {
        id: 46,
        nome: "Emirados Arabes Unidos",
        presidente: "Khalifa bin Zayed Al Nahyan",
        habitantes: 9890402,
        territorio: "83,600 km²",
      },
      {
        id: 47,
        nome: "Uzbequistao",
        presidente: "Shavkat Mirziyoyev",
        habitantes: 34169175,
        territorio: "447,400 km²",
      },
      {
        id: 48,
        nome: "Vietna",
        presidente: "Nguyen Xuan Phuc",
        habitantes: 98168838,
        territorio: "331,212 km²",
      },
      {
        id: 49,
        nome: "Iemen",
        presidente: "Abdrabbuh Mansur Hadi",
        habitantes: 30491000,
        territorio: "527,968 km²",
      },
    ],
  },
  {
    nome: "Europa",
    paises: [
      {
        id: 1,
        nome: "Albania",
        presidente: "Ilir Meta",
        habitantes: 2877797,
        territorio: "28,748 km²",
      },
      {
        id: 2,
        nome: "Alemanha",
        presidente: "Frank-Walter Steinmeier",
        habitantes: 83149300,
        territorio: "357,022 km²",
      },
      {
        id: 3,
        nome: "Andorra",
        presidente: "Xavier Espot Zamora",
        habitantes: 77265,
        territorio: "468 km²",
      },
      {
        id: 4,
        nome: "Armenia",
        presidente: "Armen Sargsyan",
        habitantes: 2963243,
        territorio: "29,743 km²",
      },
      {
        id: 5,
        nome: "Austria",
        presidente: "Alexander Van der Bellen",
        habitantes: 8917205,
        territorio: "83,879 km²",
      },
      {
        id: 6,
        nome: "Azerbaijao",
        presidente: "Ilham Aliyev",
        habitantes: 10139177,
        territorio: "86,600 km²",
      },
      {
        id: 7,
        nome: "Belgica",
        presidente: "Alexander De Croo",
        habitantes: 11589623,
        territorio: "30,528 km²",
      },
      {
        id: 8,
        nome: "Bielorrussia",
        presidente: "Alexander Lukashenko",
        habitantes: 9408400,
        territorio: "207,600 km²",
      },
      {
        id: 9,
        nome: "Bosnia e Herzegovina",
        presidente: "Milorad Dodik",
        habitantes: 3301000,
        territorio: "51,209 km²",
      },
      {
        id: 10,
        nome: "Bulgaria",
        presidente: "Rumen Radev",
        habitantes: 6948445,
        territorio: "110,994 km²",
      },
      {
        id: 11,
        nome: "Chipre",
        presidente: "Nicos Anastasiades",
        habitantes: 1207359,
        territorio: "9,251 km²",
      },
      {
        id: 12,
        nome: "Croacia",
        presidente: "Zoran Milanović",
        habitantes: 4087843,
        territorio: "56,594 km²",
      },
      {
        id: 13,
        nome: "Dinamarca",
        presidente: "Mette Frederiksen",
        habitantes: 5822763,
        territorio: "42,933 km²",
      },
      {
        id: 14,
        nome: "Eslovaquia",
        presidente: "Zuzana Čaputová",
        habitantes: 5456362,
        territorio: "49,036 km²",
      },
      {
        id: 15,
        nome: "Eslovenia",
        presidente: "Borut Pahor",
        habitantes: 2078938,
        territorio: "20,273 km²",
      },
      {
        id: 16,
        nome: "Espanha",
        presidente: "Pedro Sánchez",
        habitantes: 46723749,
        territorio: "505,992 km²",
      },
      {
        id: 17,
        nome: "Estonia",
        presidente: "Kersti Kaljulaid",
        habitantes: 1326535,
        territorio: "45,227 km²",
      },
      {
        id: 18,
        nome: "Finlandia",
        presidente: "Sauli Niinistö",
        habitantes: 5540720,
        territorio: "338,424 km²",
      },
      {
        id: 19,
        nome: "Franca",
        presidente: "Emmanuel Macron",
        habitantes: 67059887,
        territorio: "551,695 km²",
      },
      {
        id: 20,
        nome: "Georgia",
        presidente: "Salome Zurabishvili",
        habitantes: 3989167,
        territorio: "69,700 km²",
      },
      {
        id: 21,
        nome: "Grecia",
        presidente: "Katerina Sakellaropoulou",
        habitantes: 10724599,
        territorio: "131,957 km²",
      },
      {
        id: 22,
        nome: "Hungria",
        presidente: "Katalin Novák",
        habitantes: 9772756,
        territorio: "93,030 km²",
      },
      {
        id: 23,
        nome: "Irlanda",
        presidente: "Michael D. Higgins",
        habitantes: 4937786,
        territorio: "70,273 km²",
      },
      {
        id: 24,
        nome: "Islandia",
        presidente: "Guðni Th. Jóhannesson",
        habitantes: 366130,
        territorio: "103,000 km²",
      },
      {
        id: 25,
        nome: "Italia",
        presidente: "Sergio Mattarella",
        habitantes: 60244639,
        territorio: "301,340 km²",
      },
      {
        id: 26,
        nome: "Letonia",
        presidente: "Egils Levits",
        habitantes: 1886198,
        territorio: "64,589 km²",
      },
      {
        id: 27,
        nome: "Liechtenstein",
        presidente: "Daniel Risch",
        habitantes: 38128,
        territorio: "160 km²",
      },
      {
        id: 28,
        nome: "Lituania",
        presidente: "Gitanas Nausėda",
        habitantes: 2722289,
        territorio: "65,300 km²",
      },
      {
        id: 29,
        nome: "Luxemburgo",
        presidente: "Xavier Bettel",
        habitantes: 634814,
        territorio: "2,586 km²",
      },
      {
        id: 30,
        nome: "Malta",
        presidente: "George Vella",
        habitantes: 514564,
        territorio: "316 km²",
      },
      {
        id: 31,
        nome: "Moldavia",
        presidente: "Maia Sandu",
        habitantes: 2657637,
        territorio: "33,846 km²",
      },
      {
        id: 32,
        nome: "Monaco",
        presidente: "Albert Alexandre Louis Pierre Grimaldi",
        habitantes: 39242,
        territorio: "2 km²",
      },
      {
        id: 33,
        nome: "Montenegro",
        presidente: "Milo Đukanović",
        habitantes: 622359,
        territorio: "13,812 km²",
      },
      {
        id: 34,
        nome: "Noruega",
        presidente: "Jonas Gahr Støre",
        habitantes: 5421241,
        territorio: "385,207 km²",
      },
      {
        id: 35,
        nome: "Paises Baixos",
        presidente: "Mark Rutte",
        habitantes: 17134872,
        territorio: "41,543 km²",
      },
      {
        id: 36,
        nome: "Polonia",
        presidente: "Andrzej Duda",
        habitantes: 38386000,
        territorio: "312,696 km²",
      },
      {
        id: 37,
        nome: "Portugal",
        presidente: "Marcelo Rebelo de Sousa",
        habitantes: 10196709,
        territorio: "92,090 km²",
      },
      {
        id: 38,
        nome: "Reino Unido",
        presidente: "Boris Johnson",
        habitantes: 67886011,
        territorio: "242,495 km²",
      },
      {
        id: 39,
        nome: "Republica Checa",
        presidente: "Miloš Zeman",
        habitantes: 10708981,
        territorio: "78,866 km²",
      },
      {
        id: 40,
        nome: "Romenia",
        presidente: "Klaus Iohannis",
        habitantes: 19237691,
        territorio: "238,397 km²",
      },
      {
        id: 41,
        nome: "Russia",
        presidente: "Vladimir Putin",
        habitantes: 145912025,
        territorio: "17,098,242 km²",
      },
      {
        id: 42,
        nome: "San Marino",
        presidente: "Gian Carlo Venturini",
        habitantes: 33931,
        territorio: "61 km²",
      },
      {
        id: 43,
        nome: "Servia",
        presidente: "Aleksandar Vučić",
        habitantes: 6901188,
        territorio: "88,361 km²",
      },
      {
        id: 44,
        nome: "Suecia",
        presidente: "Stefan Löfven",
        habitantes: 10099265,
        territorio: "450,295 km²",
      },
      {
        id: 45,
        nome: "Suica",
        presidente: "Alain Berset",
        habitantes: 8654622,
        territorio: "41,290 km²",
      },
      {
        id: 46,
        nome: "Ucrania",
        presidente: "Volodymyr Zelensky",
        habitantes: 43733762,
        territorio: "603,500 km²",
      },
      {
        id: 47,
        nome: "Vaticano",
        presidente: "Papa Francisco",
        habitantes: 825,
        territorio: "0.44 km²",
      },
    ],
  },
  {
    nome: "Oceania",
    paises: [
      {
        id: 1,
        nome: "Austrália",
        presidente: "Jack Wilson",
        habitantes: 25000000,
        territorio: "8,000,000 km²",
      },
      {
        id: 2,
        nome: "Nova Zelândia",
        presidente: "Emma Jones",
        habitantes: 5000000,
        territorio: "300,000 km²",
      },
      {
        id: 3,
        nome: "Fiji",
        presidente: "Ravi Patel",
        habitantes: 900000,
        territorio: "18,272 km²",
      },
      {
        id: 4,
        nome: "Papua Nova Guiné",
        presidente: "Sarah Lee",
        habitantes: 9000000,
        territorio: "462,840 km²",
      },
      {
        id: 5,
        nome: "Ilhas Salomão",
        presidente: "David Smith",
        habitantes: 650000,
        territorio: "28,896 km²",
      },
      {
        id: 6,
        nome: "Vanuatu",
        presidente: "Luisa Garcia",
        habitantes: 300000,
        territorio: "12,189 km²",
      },
      {
        id: 7,
        nome: "Samoa",
        presidente: "Anna Wang",
        habitantes: 200000,
        territorio: "2,831 km²",
      },
      {
        id: 8,
        nome: "Tonga",
        presidente: "John Brown",
        habitantes: 100000,
        territorio: "747 km²",
      },
      {
        id: 9,
        nome: "Tuvalu",
        presidente: "Maria Santos",
        habitantes: 11000,
        territorio: "26 km²",
      },
      {
        id: 10,
        nome: "Kiribati",
        presidente: "Robert Nguyen",
        habitantes: 120000,
        territorio: "811 km²",
      },
      {
        id: 11,
        nome: "Micronésia",
        presidente: "Sophia Kim",
        habitantes: 110000,
        territorio: "702 km²",
      },
      {
        id: 12,
        nome: "Nauru",
        presidente: "Chris Wilson",
        habitantes: 11000,
        territorio: "21 km²",
      },
      {
        id: 13,
        nome: "Palau",
        presidente: "Oliver Martin",
        habitantes: 18000,
        territorio: "459 km²",
      },
      {
        id: 14,
        nome: "Ilhas Marshall",
        presidente: "Lucas Roberts",
        habitantes: 53000,
        territorio: "181 km²",
      },
      {
        id: 15,
        nome: "Estados Federados da Micronésia",
        presidente: "Ella Thompson",
        habitantes: 110000,
        territorio: "702 km²",
      },
    ],
  },
];

export default { estadosBrasileiros, continentes };
